name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master, main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get branch name
      id: branch-name
      run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

    - name: Validate Docker Hub username
      id: validate-username
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "Error: DOCKER_USERNAME secret is not set"
          exit 1
        fi
        echo "username=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/brickcenter_bot:${{ steps.branch-name.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

